-- =============================================================================
-- 03-rbac.sql
-- Role hierarchy and grants for the Scientific Workbench
-- Run as SECURITYADMIN / ACCOUNTADMIN
-- =============================================================================

-- Platform roles
CREATE ROLE IF NOT EXISTS WORKBENCH_ADMIN
  COMMENT = 'Full platform administration';

CREATE ROLE IF NOT EXISTS WORKBENCH_SCIENTIST
  COMMENT = 'Scientist with tool execution and data access';

CREATE ROLE IF NOT EXISTS WORKBENCH_VIEWER
  COMMENT = 'Read-only access to results and catalog';

-- Role hierarchy
GRANT ROLE WORKBENCH_SCIENTIST TO ROLE WORKBENCH_ADMIN;
GRANT ROLE WORKBENCH_VIEWER TO ROLE WORKBENCH_SCIENTIST;
GRANT ROLE WORKBENCH_ADMIN TO ROLE SYSADMIN;

-- Platform database grants
GRANT USAGE ON DATABASE SCIENTIFIC_WORKBENCH TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SCIENTIFIC_WORKBENCH TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT INSERT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT CREATE TABLE ON SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT INSERT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.PROVENANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.PROVENANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.GOVERNANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;

-- Reference data (read-only for all scientists)
GRANT USAGE ON DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;

-- Projects database
GRANT USAGE ON DATABASE WORKBENCH_PROJECTS TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKBENCH_PROJECTS TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN DATABASE WORKBENCH_PROJECTS TO ROLE WORKBENCH_SCIENTIST;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE WORKBENCH_XS TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON WAREHOUSE WORKBENCH_S TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON WAREHOUSE WORKBENCH_ML TO ROLE WORKBENCH_SCIENTIST;

-- Viewer grants (read-only)
GRANT USAGE ON DATABASE SCIENTIFIC_WORKBENCH TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON WAREHOUSE WORKBENCH_XS TO ROLE WORKBENCH_VIEWER;

-- Future grants (new objects auto-granted)
-- This script runs before steps 05+ create the tables, procedures, views and
-- semantic views, so the ALL ... grants above match nothing on a fresh
-- account. These FUTURE grants are what actually cover those objects. Schema-
-- level future grants take precedence over database-level ones, so each schema
-- that needs access is listed explicitly.
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT INSERT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE SEMANTIC VIEWS IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.WORKFLOWS TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SCIENTIFIC_WORKBENCH.WORKFLOWS TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SCIENTIFIC_WORKBENCH.WORKFLOWS TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.PROVENANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT INSERT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.PROVENANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.GOVERNANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SCIENTIFIC_WORKBENCH.GOVERNANCE TO ROLE WORKBENCH_SCIENTIST;
-- Governance procedures (agent evals, join-key validation) are admin-only.
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SCIENTIFIC_WORKBENCH.GOVERNANCE TO ROLE WORKBENCH_ADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;

-- Compute pool and image repository grants
GRANT USAGE ON COMPUTE POOL NIM_GPU_L40S_POOL TO ROLE WORKBENCH_ADMIN;
GRANT USAGE ON COMPUTE POOL NIM_GPU_A10G_POOL TO ROLE WORKBENCH_ADMIN;
GRANT USAGE ON COMPUTE POOL NIM_BUILD_POOL TO ROLE WORKBENCH_ADMIN;
GRANT READ, WRITE ON IMAGE REPOSITORY SCIENTIFIC_WORKBENCH.CATALOG.IMAGES TO ROLE WORKBENCH_ADMIN;
GRANT READ, WRITE ON IMAGE REPOSITORY SCIENTIFIC_WORKBENCH.CATALOG.NIM_GPU_IMAGES TO ROLE WORKBENCH_ADMIN;

-- Agent creation and usage grants
GRANT CREATE AGENT ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE SYSADMIN;
GRANT CREATE AGENT ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_ADMIN;

-- Schema DDL access for the admin role (validation tests, smoke tests, and
-- tool registry tests run as WORKBENCH_ADMIN and write scratch tables into
-- CATALOG / RESULTS). Search service grants live in 06-cortex-services.sql,
-- because the services do not exist yet at this step on a fresh account.
GRANT CREATE TABLE ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_ADMIN;
GRANT CREATE TABLE ON SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_ADMIN;

-- Secret grants (prerequisite objects, granted after roles exist)
-- Both secrets are created by 00-prerequisites.sql as ACCOUNTADMIN, so the
-- roles that reference them in function/procedure definitions need READ.
-- SYSADMIN deploys the NIM tools in Phase 3; without READ on NGC_API_KEY,
-- tools/nvidia/nim_image_size.sql fails with:
--   003005 (42000): Secret 'NGC_API_KEY' does not exist or operation not authorized.
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET TO ROLE WORKBENCH_ADMIN;
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET TO ROLE SYSADMIN;
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY TO ROLE WORKBENCH_ADMIN;
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY TO ROLE SYSADMIN;

-- =============================================================================
-- Task execution privilege
-- =============================================================================
-- EXECUTE TASK is an ACCOUNT-level privilege and is NOT implied by ownership.
-- Without it, `ALTER TASK ... RESUME` in 05-tool-registry.sql fails with:
--   091089 (23001): Cannot execute task, EXECUTE TASK privilege must be
--   granted to owner role
-- SYSADMIN owns CATALOG.TASK_AUTO_DISCOVER_TOOLS, so it needs the grant.
-- EXECUTE MANAGED TASK is additionally required for serverless tasks (tasks
-- declared without a WAREHOUSE); granted here so later serverless tasks work.
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE SYSADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE WORKBENCH_ADMIN;
