-- =============================================================================
-- SNOWSIGHT ACCOUNTADMIN DEPLOY SCRIPT
-- Run this ENTIRE script in Snowsight as ACCOUNTADMIN
-- This handles everything that Cortex Code's restricted session cannot do.
-- After this completes, return to Cortex Code for the remaining SYSADMIN steps.
-- =============================================================================
-- DISCLAIMER: This application is not part of the Snowflake Service and is
-- governed by the terms in LICENSE, unless expressly agreed to in writing. You
-- use this application at your own risk, and Snowflake has no obligation to
-- support your use of this application.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- STEP 0: CLEAN SLATE — Drop existing deployment
-- =============================================================================

-- Drop existing services first (they reference compute pools)
DROP SERVICE IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.SCIENTIFIC_WORKBENCH_WEB;

-- Drop existing databases
DROP DATABASE IF EXISTS SCIENTIFIC_WORKBENCH;
DROP DATABASE IF EXISTS WORKBENCH_REFERENCE;
DROP DATABASE IF EXISTS WORKBENCH_PROJECTS;

-- Drop existing warehouses
DROP WAREHOUSE IF EXISTS WORKBENCH_XS;
DROP WAREHOUSE IF EXISTS WORKBENCH_S;
DROP WAREHOUSE IF EXISTS WORKBENCH_ML;
DROP WAREHOUSE IF EXISTS WORKBENCH_WH;

-- Drop old roles (from prior deployment)
DROP ROLE IF EXISTS WORKBENCH_ADMIN;
DROP ROLE IF EXISTS WORKBENCH_SCIENTIST;
DROP ROLE IF EXISTS WORKBENCH_VIEWER;
DROP ROLE IF EXISTS WORKBENCH_SCIENTIST_FULL;
DROP ROLE IF EXISTS WORKBENCH_SCIENTIST_READ;
DROP ROLE IF EXISTS WORKBENCH_DATA_ENGINEER;
DROP ROLE IF EXISTS WORKBENCH_LEADERSHIP;
DROP ROLE IF EXISTS WORKBENCH_EXTERNAL;

-- =============================================================================
-- STEP 1: CREATE DATABASES AND SCHEMAS (from 01-databases-and-schemas.sql)
-- =============================================================================

-- Platform database
CREATE DATABASE SCIENTIFIC_WORKBENCH
  COMMENT = 'Snowflake Scientific Workbench — platform infrastructure';

USE DATABASE SCIENTIFIC_WORKBENCH;

CREATE SCHEMA CATALOG COMMENT = 'Asset catalog, tool registry, search services';
CREATE SCHEMA GOVERNANCE COMMENT = 'Audit trail, canary assertions, data quality';
CREATE SCHEMA PROVENANCE COMMENT = 'Immutable provenance log for all actions';
CREATE SCHEMA RESULTS COMMENT = 'Agent and tool execution outputs';
CREATE SCHEMA WORKFLOWS COMMENT = 'Template+Agent workflow engine';

-- Reference data database
CREATE DATABASE WORKBENCH_REFERENCE
  COMMENT = 'Public reference datasets for life sciences R&D';

USE DATABASE WORKBENCH_REFERENCE;
CREATE SCHEMA CHEMBL COMMENT = 'ChEMBL — compounds, targets, activities (~30GB)';
CREATE SCHEMA PROTEIN COMMENT = 'UniProt Swiss-Prot — protein sequences and annotations (~5GB)';
CREATE SCHEMA PATHWAYS COMMENT = 'Gene Ontology, Reactome, MSigDB — pathways and gene sets';
CREATE SCHEMA GENOMICS COMMENT = 'HGNC gene nomenclature, GTEx expression';
CREATE SCHEMA CLINICAL COMMENT = 'ClinicalTrials.gov structured data';
CREATE SCHEMA DRUGS COMMENT = 'DrugBank — drug information and targets';

-- Projects database
CREATE DATABASE WORKBENCH_PROJECTS
  COMMENT = 'Customer project data — one schema per project';

USE DATABASE WORKBENCH_PROJECTS;
CREATE SCHEMA DEMO_NSCLC COMMENT = 'Demo project: KRAS G12C resistance in NSCLC';
CREATE SCHEMA SHARED_ANALYTICS COMMENT = 'Cross-project analytics views';

-- SAR prerequisites
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_APPS
  COMMENT = 'Code storage and workspace for Snowflake App Runtime (SAR) apps';

CREATE WAREHOUSE IF NOT EXISTS SNOWFLAKE_APPS_QUERY_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Query warehouse for the Scientific Workbench SAR app';

GRANT USAGE ON DATABASE SNOWFLAKE_APPS TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_APPS_QUERY_WH TO ROLE SYSADMIN;

-- =============================================================================
-- STEP 2: WAREHOUSES AND COMPUTE POOLS (from 02-warehouses.sql)
-- =============================================================================

USE ROLE SYSADMIN;

CREATE WAREHOUSE WORKBENCH_XS
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Catalog operations, metadata queries, agent orchestration';

CREATE WAREHOUSE WORKBENCH_S
  WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Interactive analysis, DE computation, tool execution';

CREATE WAREHOUSE WORKBENCH_ML
  WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ML model training, batch scoring, heavy transforms';

-- SPCS Compute Pools
USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL IF NOT EXISTS WORKBENCH_CPU_POOL
  MIN_NODES = 1 MAX_NODES = 3 INSTANCE_FAMILY = CPU_X64_S
  AUTO_SUSPEND_SECS = 600 AUTO_RESUME = TRUE
  COMMENT = 'SPCS CPU pool: React app hosting, RDKit, general containers';

CREATE COMPUTE POOL IF NOT EXISTS WORKBENCH_APP_POOL
  MIN_NODES = 1 MAX_NODES = 2 INSTANCE_FAMILY = CPU_X64_S
  AUTO_SUSPEND_SECS = 900 AUTO_RESUME = TRUE
  COMMENT = 'SPCS pool for React Scientific Workbench app hosting';

CREATE COMPUTE POOL IF NOT EXISTS NIM_GPU_A10G_POOL
  MIN_NODES = 1 MAX_NODES = 2 INSTANCE_FAMILY = GPU_NV_S
  AUTO_SUSPEND_SECS = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'NIM GPU pool (A10G 24 GiB): GenMol, ProteinMPNN, MolMIM, OpenFold2';

CREATE COMPUTE POOL IF NOT EXISTS NIM_GPU_L40S_POOL
  MIN_NODES = 1 MAX_NODES = 2 INSTANCE_FAMILY = GPU_L40S_G1_16
  AUTO_SUSPEND_SECS = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'NIM GPU pool (L40S 48 GiB): Boltz-2, DiffDock, RFdiffusion, OpenFold3';

CREATE COMPUTE POOL IF NOT EXISTS NIM_BUILD_POOL
  MIN_NODES = 1 MAX_NODES = 1 INSTANCE_FAMILY = GEN_X64_G2_32
  AUTO_SUSPEND_SECS = 120 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'CPU pool for NIM image mirroring. No GPU needed.';

-- Image Repositories
CREATE IMAGE REPOSITORY IF NOT EXISTS SCIENTIFIC_WORKBENCH.CATALOG.IMAGES
  COMMENT = 'Container images for SPCS services';

CREATE IMAGE REPOSITORY IF NOT EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NIM_GPU_IMAGES
  COMMENT = 'Mirrored NVIDIA NIM images from nvcr.io for SPCS GPU inference';

-- =============================================================================
-- STEP 3: PREREQUISITES — Network Rules, EAI, Secrets (from 00-prerequisites.sql)
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE SCIENTIFIC_WORKBENCH;
USE SCHEMA CATALOG;

-- Network rule for NVIDIA BioNeMo API
CREATE NETWORK RULE IF NOT EXISTS NVIDIA_API_NETWORK_RULE
  MODE = EGRESS TYPE = HOST_PORT
  VALUE_LIST = ('api.nvcf.nvidia.com:443','integrate.api.nvidia.com:443','health.api.nvidia.com:443','files.rcsb.org:443')
  COMMENT = 'Allow outbound access to NVIDIA BioNeMo hosted NIM endpoints + PDB';

-- NVIDIA API Key Secret
CREATE OR REPLACE SECRET SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET
  TYPE = GENERIC_STRING
  SECRET_STRING = 'REPLACE_WITH_YOUR_NVIDIA_API_KEY'
  COMMENT = 'NVIDIA BioNeMo API key from build.nvidia.com — stored encrypted';

-- External Access Integration for NVIDIA API
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION NVIDIA_API_EAI
  ALLOWED_NETWORK_RULES = (NVIDIA_API_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET)
  ENABLED = TRUE
  COMMENT = 'External access to NVIDIA BioNeMo NIM hosted endpoints';

GRANT USAGE ON INTEGRATION NVIDIA_API_EAI TO ROLE SYSADMIN;

-- NGC API Key (placeholder — set later if needed for SPCS NIM containers)
CREATE SECRET IF NOT EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY
  TYPE = GENERIC_STRING
  SECRET_STRING = 'REPLACE_WITH_YOUR_NGC_API_KEY'
  COMMENT = 'NGC API key for NIM container pull and runtime weight download';

-- NGC Registry Pull
CREATE NETWORK RULE IF NOT EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NGC_REGISTRY_PULL
  MODE = EGRESS TYPE = HOST_PORT
  VALUE_LIST = ('nvcr.io:443','*.nvcf.nvidia.com:443','auth.docker.io:443','production.cloudflare.docker.com:443')
  COMMENT = 'Egress for pulling NIM images from NGC container registry';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION NGC_REGISTRY_PULL_EAI
  ALLOWED_NETWORK_RULES = (SCIENTIFIC_WORKBENCH.CATALOG.NGC_REGISTRY_PULL)
  ALLOWED_AUTHENTICATION_SECRETS = (SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY)
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION NGC_REGISTRY_PULL_EAI TO ROLE SYSADMIN;

-- NIM Runtime Egress
CREATE NETWORK RULE IF NOT EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NIM_RUNTIME_EGRESS
  MODE = EGRESS TYPE = HOST_PORT
  VALUE_LIST = ('nvcr.io:443','*.nvcf.nvidia.com:443','*.ngc.nvidia.com:443','*.download.nvidia.com:443','huggingface.co:443','*.huggingface.co:443')
  COMMENT = 'Egress for NIM runtime weight download';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION NIM_RUNTIME_EAI
  ALLOWED_NETWORK_RULES = (SCIENTIFIC_WORKBENCH.CATALOG.NIM_RUNTIME_EGRESS)
  ALLOWED_AUTHENTICATION_SECRETS = (SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY)
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION NIM_RUNTIME_EAI TO ROLE SYSADMIN;

-- PDB API
CREATE NETWORK RULE IF NOT EXISTS SCIENTIFIC_WORKBENCH.CATALOG.PDB_API_RULE
  TYPE = HOST_PORT MODE = EGRESS
  VALUE_LIST = ('data.rcsb.org:443', 'files.rcsb.org:443')
  COMMENT = 'Access to RCSB PDB REST API';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION PDB_API_EAI
  ALLOWED_NETWORK_RULES = (SCIENTIFIC_WORKBENCH.CATALOG.PDB_API_RULE)
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION PDB_API_EAI TO ROLE SYSADMIN;

-- =============================================================================
-- STEP 4: RBAC (from 03-rbac.sql)
-- =============================================================================

USE ROLE SECURITYADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS WORKBENCH_ADMIN COMMENT = 'Full platform administration';
CREATE ROLE IF NOT EXISTS WORKBENCH_SCIENTIST COMMENT = 'Scientist with tool execution and data access';
CREATE ROLE IF NOT EXISTS WORKBENCH_VIEWER COMMENT = 'Read-only access to results and catalog';

-- Role hierarchy
GRANT ROLE WORKBENCH_SCIENTIST TO ROLE WORKBENCH_ADMIN;
GRANT ROLE WORKBENCH_VIEWER TO ROLE WORKBENCH_SCIENTIST;
GRANT ROLE WORKBENCH_ADMIN TO ROLE SYSADMIN;

-- Grant WORKBENCH_SCIENTIST to current user
GRANT ROLE WORKBENCH_SCIENTIST TO USER DATNOOR;
GRANT ROLE WORKBENCH_ADMIN TO USER DATNOOR;

USE ROLE ACCOUNTADMIN;

-- Platform database grants
GRANT USAGE ON DATABASE SCIENTIFIC_WORKBENCH TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SCIENTIFIC_WORKBENCH TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT INSERT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT CREATE TABLE ON SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT INSERT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.PROVENANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.PROVENANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.GOVERNANCE TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;

-- Reference data
GRANT USAGE ON DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;

-- Projects
GRANT USAGE ON DATABASE WORKBENCH_PROJECTS TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKBENCH_PROJECTS TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN DATABASE WORKBENCH_PROJECTS TO ROLE WORKBENCH_SCIENTIST;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE WORKBENCH_XS TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON WAREHOUSE WORKBENCH_S TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON WAREHOUSE WORKBENCH_ML TO ROLE WORKBENCH_SCIENTIST;
GRANT USAGE ON WAREHOUSE WORKBENCH_XS TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE WORKBENCH_S TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE WORKBENCH_ML TO ROLE SYSADMIN;

-- Viewer grants
GRANT USAGE ON DATABASE SCIENTIFIC_WORKBENCH TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON WAREHOUSE WORKBENCH_XS TO ROLE WORKBENCH_VIEWER;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.RESULTS TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN DATABASE WORKBENCH_REFERENCE TO ROLE WORKBENCH_SCIENTIST;

-- Compute pool grants
GRANT USAGE ON COMPUTE POOL NIM_GPU_L40S_POOL TO ROLE WORKBENCH_ADMIN;
GRANT USAGE ON COMPUTE POOL NIM_GPU_A10G_POOL TO ROLE WORKBENCH_ADMIN;
GRANT USAGE ON COMPUTE POOL NIM_BUILD_POOL TO ROLE WORKBENCH_ADMIN;
GRANT READ, WRITE ON IMAGE REPOSITORY SCIENTIFIC_WORKBENCH.CATALOG.IMAGES TO ROLE WORKBENCH_ADMIN;
GRANT READ, WRITE ON IMAGE REPOSITORY SCIENTIFIC_WORKBENCH.CATALOG.NIM_GPU_IMAGES TO ROLE WORKBENCH_ADMIN;

-- Agent grants
GRANT CREATE AGENT ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE SYSADMIN;
GRANT CREATE AGENT ON SCHEMA SCIENTIFIC_WORKBENCH.CATALOG TO ROLE WORKBENCH_ADMIN;

-- Secret grants
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET TO ROLE WORKBENCH_ADMIN;
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET TO ROLE SYSADMIN;
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY TO ROLE WORKBENCH_ADMIN;
GRANT READ ON SECRET SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY TO ROLE SYSADMIN;

-- Task execution
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE SYSADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE WORKBENCH_ADMIN;

-- Ownership transfer for SYSADMIN to manage objects
GRANT OWNERSHIP ON DATABASE SCIENTIFIC_WORKBENCH TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE SCIENTIFIC_WORKBENCH TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE WORKBENCH_REFERENCE TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE WORKBENCH_REFERENCE TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE WORKBENCH_PROJECTS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE WORKBENCH_PROJECTS TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Cortex Agent database roles
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE WORKBENCH_SCIENTIST;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE WORKBENCH_SCIENTIST;

-- =============================================================================
-- DONE! Return to Cortex Code for SYSADMIN steps (tool registry, tools,
-- agents, semantic views, data loading, app deployment).
-- =============================================================================

SELECT 'ACCOUNTADMIN setup complete! Return to Cortex Code.' AS status;
