-- =============================================================================
-- scripts/teardown.sql
-- Snowflake Scientific Workbench — Complete Teardown Script
-- Run as ACCOUNTADMIN
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Suspend and drop tasks
ALTER TASK IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.TOOL_DISCOVERY_TASK SUSPEND;
DROP TASK IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.TOOL_DISCOVERY_TASK;
ALTER TASK IF EXISTS SCIENTIFIC_WORKBENCH.GOVERNANCE.CHECK_CANARIES_TASK SUSPEND;
DROP TASK IF EXISTS SCIENTIFIC_WORKBENCH.GOVERNANCE.CHECK_CANARIES_TASK;

-- 2. Drop SAR App and Application Services
DROP APPLICATION SERVICE IF EXISTS SNOWFLAKE_APPS.PUBLIC.SCIENTIFIC_WORKBENCH_APP;
DROP SERVICE IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.WORKBENCH_APP_SERVICE;
DROP SERVICE IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NIM_BOLTZ2_SVC;

-- 3. Drop Cortex Agents
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.DISCOVERY_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.SCIENTIFIC_WORKBENCH_ROUTER;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.ORCHESTRATOR_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.WORKFLOW_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.GENOMICS_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.CHEMISTRY_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.STRUCTURAL_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.CLINICAL_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.CUSTOM_TOOLS_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.COMPUTATIONAL_BIOLOGY_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.MEDICINAL_CHEMISTRY_AGENT;
DROP AGENT IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.STRUCTURAL_BIOLOGY_AGENT;

-- 4. Drop Integrations, Secrets, Network Rules
DROP INTEGRATION IF EXISTS NVIDIA_API_EAI;
DROP INTEGRATION IF EXISTS NIM_RUNTIME_EAI;
DROP SECRET IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_SECRET;
DROP SECRET IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NGC_API_KEY;
DROP NETWORK RULE IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NVIDIA_API_NETWORK_RULE;
DROP NETWORK RULE IF EXISTS SCIENTIFIC_WORKBENCH.CATALOG.NIM_CONTAINER_NETWORK_RULE;

-- 5. Drop Compute Pools
DROP COMPUTE POOL IF EXISTS WORKBENCH_BUILD_POOL;
DROP COMPUTE POOL IF EXISTS WORKBENCH_CPU_POOL;
DROP COMPUTE POOL IF EXISTS NIM_GPU_L40S_POOL;
DROP COMPUTE POOL IF EXISTS NIM_GPU_A10G_POOL;

-- 6. Drop Databases
DROP DATABASE IF EXISTS SCIENTIFIC_WORKBENCH;
DROP DATABASE IF EXISTS WORKBENCH_REFERENCE;
DROP DATABASE IF EXISTS WORKBENCH_PROJECTS;

-- 7. Drop Warehouses
DROP WAREHOUSE IF EXISTS WORKBENCH_XS;
DROP WAREHOUSE IF EXISTS WORKBENCH_S;
DROP WAREHOUSE IF EXISTS WORKBENCH_ML;

-- 8. Drop Roles
DROP ROLE IF EXISTS WORKBENCH_ADMIN;
DROP ROLE IF EXISTS WORKBENCH_SCIENTIST;
DROP ROLE IF EXISTS WORKBENCH_VIEWER;
